---

- name: run "apt-get" update
  become: true
  apt:
    update_cache: yes

- name: run "apt-get" libmicrohttpd-dev libssl-dev cmake build-essential libhwloc-dev
  become: true
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - libmicrohttpd-dev
    - libssl-dev
    - cmake
    - build-essential
    - libhwloc-dev 

- name: check if xmr-stak repo exists
  stat: 
    path: /home/r3lik/xmr-stak
  register: stat_result_xmr_stak
  
- debug:
    msg: "Path exists and is a directory"
  when: stat_result_xmr_stak.stat.isdir is defined and stat_result_xmr_stak.stat.isdir 

- name: git clone xmr-stak
  git:
    clone: yes
    dest: /home/r3lik/xmr-stak
    repo: 'https://github.com/fireice-uk/xmr-stak.git'
  when: stat_result_xmr_stak.stat.isdir is defined and stat_result_xmr_stak.stat.isdir == False

- name: create directories 
  file:
    path: /home/r3lik/xmr-stak/build
    state: directory
    mode: 0755

- name: check if cpu.txt file exists
  stat:
    path: /home/r3lik/xmr-stak/build/bin/cpu.txt
  register: stat_result_cpu

- name: check if donate file exists
  stat:
    path: /home/r3lik/xmr-stak/xmrstak/donate-level.hpp
  register: stat_result_donate

- name: run cmake
  command: cmake .. -DCUDA_ENABLE=OFF -DOpenCL_ENABLE=OFF
  args:
    chdir: /home/r3lik/xmr-stak/build
  when: stat_result_donate.stat.exists == False

#- name: copy donate file
#  copy:
#    src: /files/donate-level.hpp
#    dest: /home/r3lik/xmr-stak/xmrstak/donate-level.hpp

- name: run make install
  command: make install
  args:
    chdir: /home/r3lik/xmr-stak/build
  when: stat_result_cpu.stat.exists == False

#- name: copy config files
#  copy: 
#    src: /files/config.txt
#    dest: /home/r3lik/xmr-stak/build/bin/config.txt
