---

- name: run "apt-get" update
  become: true
  apt:
    update_cache: yes

- name: run "apt-get" libmicrohttpd-dev libssl-dev cmake build-essential libhwloc-dev
  become: true
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - vim
    - tmux
    - htop
    - git
    - libmicrohttpd-dev
    - libssl-dev
    - cmake
    - build-essential
    - libhwloc-dev 

- name: check if xmr-stak repo exists
  stat: 
    path: /home/r3lik/xmr-stak
  register: stat_result_xmr_stak
  
- debug:
    msg: "xmr-stak path exists and is a directory"
  when: stat_result_xmr_stak.stat.isdir is defined and stat_result_xmr_stak.stat.isdir 

- name: git clone xmr-stak
  git:
    clone: yes
    dest: /home/r3lik/xmr-stak
    repo: 'https://github.com/fireice-uk/xmr-stak.git'
  when: not stat_result_xmr_stak.stat.exists

- name: create directories 
  file:
    path: /home/r3lik/xmr-stak/build
    state: directory
    mode: 0755

- name: copy donate file
  copy:
    src: donate-level.hpp
    dest: /home/r3lik/xmr-stak/xmrstak/donate-level.hpp
    owner: r3lik
    group: r3lik
    mode: 0664

- name: check if donate file exists
  stat:
    path: /home/r3lik/xmr-stak/xmrstak/donate-level.hpp
  register: stat_result_donate

- debug:
    msg: "donate file exists"
  when: stat_result_donate.stat.exists 

- name: set hugepages=128
  command: sysctl -w vm.nr_hugepages=128

- name: run cmake
  command: cmake .. -DCUDA_ENABLE=OFF -DOpenCL_ENABLE=OFF
  args:
    chdir: /home/r3lik/xmr-stak/build
#  when: stat_result_donate.stat.exists == False

- name: run make install
  command: make install
  args:
    chdir: /home/r3lik/xmr-stak/build
#  when: stat_result_cpu.stat.exists == False

- name: copy config files for 7777 pool
  copy: 
    src: config.txt
    dest: /home/r3lik/xmr-stak/build/bin/config.txt
    owner: r3lik
    group: r3lik
    mode: 0664
  when: provider == 'centurylink'

- name: copy config files for 5555 pool
  copy: 
    src: config-5555.txt
    dest: /home/r3lik/xmr-stak/build/bin/config.txt
    owner: r3lik
    group: r3lik
    mode: 0664
  when: provider == 'aruba'

- name: copy no power limit cpu config file
  copy:
    src: cpu-max.txt
    dest: /home/r3lik/xmr-stak/build/bin/cpu.txt
  when: provider == 'centurylink' 

- name: copy Aruba CPU config file
  copy:
    src: cpu-aruba.txt
    dest: /home/r3lik/xmr-stak/build/bin/cpu.txt
  when: provider == 'aruba' 

#- debug:
#    msg: "provider is {{ provider }}"
#  when: provider == 'centurylink'

#- name: check if cpu.txt file exists
#  stat:
#    path: /home/r3lik/xmr-stak/build/bin/cpu.txt
#  register: stat_result_cpu

#- debug:
#    msg: "cpu.txt exists"
#  when: stat_result_cpu.stat.exists 
