---

# Sometimes uses a lot of CPU on small VPS instances
- name: stop fail2ban
  become: true
  service:
    name: fail2ban
    state: stopped
 # become: true
 # command: service fail2ban stop

- name: run "apt-get" update
  become: true
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: run "apt-get" libmicrohttpd-dev libssl-dev cmake build-essential libhwloc-dev
  become: true
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - vim
    - tmux
    - htop
    - git
    - libmicrohttpd-dev
    - libssl-dev
    - cmake
    - build-essential
    - libhwloc-dev 
    - cpulimit

- name: check if xmr-stak repo exists
  stat: 
    path: /home/r3lik/xmr-stak
  register: stat_result_xmr_stak
  
- debug:
    msg: "xmr-stak path exists and is a directory"
  when: stat_result_xmr_stak.stat.isdir is defined and stat_result_xmr_stak.stat.isdir 

- name: git clone xmr-stak
  git:
    clone: yes
    dest: /home/r3lik/xmr-stak
    repo: 'https://github.com/fireice-uk/xmr-stak.git'
  when: not stat_result_xmr_stak.stat.exists

- name: create directories 
  file:
    path: /home/r3lik/xmr-stak/build
    state: directory
    mode: 0755

- name: copy donate file
  copy:
    src: donate-level.hpp
    dest: /home/r3lik/xmr-stak/xmrstak/donate-level.hpp
    owner: r3lik
    group: r3lik
    mode: 0664

- name: check if donate file exists
  stat:
    path: /home/r3lik/xmr-stak/xmrstak/donate-level.hpp
  register: stat_result_donate

- debug:
    msg: "donate file exists"
  when: stat_result_donate.stat.exists 

- name: set hugepages=128
  become: true
  command: sysctl -w vm.nr_hugepages=128

- name: run cmake
  command: cmake .. -DCUDA_ENABLE=OFF -DOpenCL_ENABLE=OFF
  args:
    chdir: /home/r3lik/xmr-stak/build

- name: run make install
  command: make install
  args:
    chdir: /home/r3lik/xmr-stak/build

- name: copy config files for 7777 pool
  copy: 
    src: config.txt
    dest: /home/r3lik/xmr-stak/build/bin/config.txt
    owner: r3lik
    group: r3lik
    mode: 0664
  when: provider == 'centurylink'

- name: copy config file from template
  template:
    src: config.j2
    dest: /home/r3lik/xmr-stak/build/bin/config.txt
  tags:
    - config

- name: copy no power limit cpu config file
  copy:
    src: cpu-max.txt
    dest: /home/r3lik/xmr-stak/build/bin/cpu.txt
  when: provider == 'centurylink' 

- name: copy Aruba CPU config file
  copy:
    src: cpu-aruba.txt
    dest: /home/r3lik/xmr-stak/build/bin/cpu.txt
  when: provider == 'aruba' 
